In [1]:
import numpy as np

### 어레이 모양 변형

**reshape()** : 지정된 튜플의 모양으로 주어진 어레이 모양 변형
* 항목의 수만 같으면  임의 차원의 어레이를 임의 차원의 어레이로 변경 가능
* -1 사용시 값이 자동으로 지정됨.

In [ ]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
arr.reshape(4,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### 차원 추가

In [11]:
a = np.random.rand(5)
a

array([0.640274  , 0.11793788, 0.85344178, 0.92218685, 0.27917976])

In [17]:
a[:, np.newaxis] #reshape(5,1)과 동일

array([[0.640274  ],
       [0.11793788],
       [0.85344178],
       [0.92218685],
       [0.27917976]])

In [18]:
a[np.newaxis, :] #reshape(1,5)와 동일

array([[0.640274  , 0.11793788, 0.85344178, 0.92218685, 0.27917976]])

**ravel() 과 flatten()** : 1차원 어레이 반환
* ravel()메서드는 view를 사용하여 반환된 어레이 변경시 원래 어레이도 같이 변경
* flatten() 메서드는 어레이를 새로생성

In [14]:
arr = np.arange(15).reshape(5,3)

In [15]:
arr1 = arr.ravel()
print(arr1)
arr1[0] = 99
print(arr) # arr값이 변경됨

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [16]:
arr2 = arr.flatten()
arr2

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 어레이 분열/결합

In [19]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**axis 축**
+ axis = 0 -> 행 (열 방향/ 수직)
+ axis = 1 -> 열 (행 방향/ 수평)

In [20]:
print(x.sum(axis=0))
print(x.sum(axis=1))

[30 34 38 42 46]
[10 35 60 85]


np.split(행렬, [인덱스], axis) : 지정된 기준에 따라 쪼갬

In [21]:
np.split(x, [2,3], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [22]:
np.split(x, [1,3], axis =1)

[array([[ 0],
        [ 5],
        [10],
        [15]]), array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

**np.vsplit()/np.hsplit()**
* vsplit은 axis = 0
* hsplit은 axis = 1

In [23]:
np.vsplit(x, [2,3]) # np.split(x, [2,3], axis=0)와 같음

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [24]:
np.hsplit(x,[1,3]) #np.split(x, [1,3], axis =1)와 같음

[array([[ 0],
        [ 5],
        [10],
        [15]]), array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

np.concatenate() : 두개의 어레이를 이어붙인다.
- axis=0 : 위아래(행)로 이어붙이기
- axis=1 : 좌우(열)로 이어붙이기

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

**np.vstack()/np.hstack()**
* vstack은 axis = 0
* hstack은 axis = 1

In [29]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

np.r_[ ] = np.vstack()

np.c_[ ] = np.hstack()

In [32]:
np.r_[arr1, arr2]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.c_[arr1, arr2]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 브로드캐스팅

모양이 다른 두 어레이의 연산이 가능한 경우, 브로드캐스팅 작동
- 하나의 정수와 하나의 어레이

In [33]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
arr*4

array([[ 0,  4,  8],
       [12, 16, 20]])

- 열이 같은 1차원 어레이와 2차원 어레이

In [40]:
arr2 = np.arange(4).reshape((4,1)).repeat(3,axis=1)
arr2 #reapeat() : 축에대해 지정된 숫자만큼 반복

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [41]:
arr3 = np.arange(1, 4)
arr3

array([1, 2, 3])

In [42]:
arr2 + arr3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

- 행은 같지만 열이 다른 두 2차원 어레이

In [43]:
arr4 = np.arange(1, 5).reshape((4,1))
arr4

array([[1],
       [2],
       [3],
       [4]])

In [44]:
arr2 + arr4

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])