In [1]:
import numpy as np

리스트/튜플로 어레이 생성

In [9]:
data1 = [[6, 7, 5], [8, 0, 1]]
data2 = (1,2,3,4,5)
arr1 = np.array(data1)
arr2 = np.array(data2)
print(arr1)
arr2

[[6 7 5]
 [8 0 1]]


array([1, 2, 3, 4, 5])

arr.shape 튜플로 모양 반환

In [10]:
arr1.shape

(2, 3)

arr.dtype 자료형 보여줌

In [12]:
arr1.dtype

dtype('int64')

arr.ndim 차원 보여줌

In [13]:
arr1.ndim

2

**어레이 생성 함수**
- array()
- asarray()
- arange()
- ones()
- zeros()
- empty()
- full()
- eye(), identity()

In [17]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

dtype으로 자료형 정하기

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr1.dtype

dtype('float64')

astype으로 자료형 강제 변환

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [28]:
arr2 = arr.astype(np.float64)
arr2.dtype

dtype('float64')

사용자 정의 dtype

In [39]:
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, 3)])
x = np.array([('사라', (60, 70.6, 88.5)), ('존', (80.3, 77.9, 91))], dtype=dt)

In [40]:
x.dtype

dtype([('name', '<U16'), ('grades', '<f8', (3,))])

In [41]:
x

array([('사라', [60. , 70.6, 88.5]), ('존', [80.3, 77.9, 91. ])],
      dtype=[('name', '<U16'), ('grades', '<f8', (3,))])

In [42]:
x[0]

('사라', [60. , 70.6, 88.5])

In [43]:
x[0]['name']

'사라'

In [45]:
x[0]['grades']

array([60. , 70.6, 88.5])

In [46]:
x[1]

('존', [80.3, 77.9, 91. ])

In [47]:
x[1]['name']

'존'

In [48]:
x[1]['grades']

array([80.3, 77.9, 91. ])

어레이 연산

In [49]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr2 = np.array([[3., 4., 1.], [7., 2., 12.]])
arr2

array([[ 3.,  4.,  1.],
       [ 7.,  2., 12.]])

In [51]:
arr + arr2

array([[ 4.,  6.,  4.],
       [11.,  7., 18.]])

In [52]:
arr * arr2

array([[ 3.,  8.,  3.],
       [28., 10., 72.]])

In [53]:
arr - arr2

array([[-2., -2.,  2.],
       [-3.,  3., -6.]])

In [54]:
arr/ arr2

array([[0.33333333, 0.5       , 3.        ],
       [0.57142857, 2.5       , 0.5       ]])

In [55]:
arr % arr2

array([[1., 2., 0.],
       [4., 1., 6.]])

In [56]:
arr > arr2

array([[False, False,  True],
       [False,  True, False]])