import numpy

In [1]:
import numpy as np

###인덱싱과 슬라이싱


인덱싱/슬라이싱 모두 리스트와 동일

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[5:9]

array([5, 6, 7, 8])

In [5]:
arr[3:8] = 10
arr

array([ 0,  1,  2, 10, 10, 10, 10, 10,  8,  9])

###뷰

- 넘파이는 슬라이싱 실행 시 지정된 구간을 새로 생성하는게 아님
- 그 곳을 계속 주시하는 **뷰** 생성
- 따라서 슬라이싱한 곳을 바꿔도 원본이 바뀜

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [14]:
arr_slice[:] = 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

copy() 메서드를 이용하여 해결

In [15]:
arr_slice2 = arr[5:8].copy()
arr_slice2

array([10, 10, 10])

In [17]:
arr_slice2[:] = 100
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

### 2/3차원 어레이 인덱싱, 슬라이싱

- 슬라이싱은 [ ] 1개만 됨
- [ ][ ] 슬라이싱 시 앞에것만 적용됨

**2차원**

리스트랑 똑같이 가능

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[0][2]

3

이런 식으로 더 편하게 가능

In [25]:
arr2d[0, 2]

3

In [29]:
arr2d[1:3, 0:2]

array([[4, 5],
       [7, 8]])

**3차원**

똑같음

In [37]:
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                  
                  [[7, 8, 9], 
                   [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr3d[0:2, 1, 0:3]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [54]:
arr3d[(0,1), 0, 0:2]

array([[1, 2],
       [7, 8]])

### 부울 인덱싱

In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [59]:
bob = (names == 'Bob')
bob

array([ True, False, False,  True, False, False, False])

In [60]:
names[bob]

array(['Bob', 'Bob'], dtype='<U4')

마스크 사용

In [69]:
mask = (names == 'Joe') | (names == 'Will') #부울연산자 ~ & |
names[mask]

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')